// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TmsApi.Data;

#nullable disable

namespace TmsApi.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20260704100500_AddStudentSoftDelete")]
    partial class AddStudentSoftDelete
    {
    }
}